- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/manager/manager-configmap.yaml
Enable metrics on manager when `Values.manager.metrics.enable` is `true`
There was a missing config field to really enable metrics: `enable: true`
> Enable metrics on manager

- charts/nydus-snapshotter/.helmignore
- charts/nydus-snapshotter/Chart.yaml
- charts/nydus-snapshotter/README.md
- charts/nydus-snapshotter/README.md.gotmpl
- charts/nydus-snapshotter/templates/NOTES.txt
- charts/nydus-snapshotter/templates/_helpers.tpl
- charts/nydus-snapshotter/templates/nydus-snapshotter/snapshotter-configmap.yaml
- charts/nydus-snapshotter/templates/nydus-snapshotter/snapshotter-daemonset.yaml
- charts/nydus-snapshotter/templates/nydus-snapshotter/snapshotter-rbac.yaml
- charts/nydus-snapshotter/values.yaml
Add new chart for nydus-snapshotter includes:
- daemonset for running nydus-snapshotter inside containers
- a configmap for configuring nydus-snapshotter
Fixes: #127 
Signed-off-by: bin liu <liubin0329@gmail.com>
> add chart for nydus-snapshotter

- INSTALL.md
- README.md
Add tutorial for quickly deploy Dragonfly+Nydus using Helm
We already have helm charts for Dragonfly and Nydus, but there is currently a lack of a document to combine them, so a new document is added to solve this problem.
> feat: add tutorial for quickly deploy Dragonfly+Nydus using Helm

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
when containerRuntime.containerd.registries addr is http then generate cert.d file name err
https://github.com/dragonflyoss/Dragonfly2/issues/2527
> fix registries is http generate cert.d file name err

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
There is incorrect regex in dfdaemon-daemonset, when injecting registry auth into containerd config.toml, will generate duplicate entries, which leads to containerd down after changing config.toml
Fix the regex, then should be okay.
> fix regex when checking containerd config.toml

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
Fix the regex when injecting v1 mirror settings.
[dragonflyoss/Dragonfly2#2527](https://github.com/dragonflyoss/Dragonfly2/issues/2527)
> fix the regex when injecting v1 mirror settings

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
Fix the helm template of dfdaemon, the position of command flag '--' is incorrect.
[deploy Dragonfly in K8S with Helm but HTTP(s) Proxy of docker failed to automatically configure](https://github.com/dragonflyoss/Dragonfly2/issues/2581)
Enable Docker's HTTP(s) proxy to be injected correctly and take effect.
> Fix command flag '--' for dfdaemon

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/values.yaml
> feat: add resource and registryTimeout to config

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
env: Aliyun ACK
kubernetes: 1.22.15-aliyun.1
containerd: 1.5.13
this commit is for checking the helm script dfdaemon init script's containerd init line exist, then append the cert config after it
this commit is for checking the line exist, then append the cert config after it
if `[plugins."io.containerd.grpc.v1.cri".registry]` exists in containerd config file, will insert duplicated line `[plugins."io.containerd.grpc.v1.cri".registry]`, which will cause  a containerd fatal error:
```
Aug 11 15:00:34  systemd[1]: containerd.service holdoff time over, scheduling restart.
Aug 11 15:00:34  systemd[1]: Stopped containerd container runtime.
Aug 11 15:00:34  systemd[1]: Starting containerd container runtime...
Aug 11 15:00:34  containerd[501622]: containerd: failed to load TOML: …
```
> fix bug cause 'plugins."io.containerd.grpc.v1.cri".registry' duplicated

- charts/nydus-snapshotter/Chart.yaml
- charts/nydus-snapshotter/README.md
- charts/nydus-snapshotter/README.md.gotmpl
There is no version 1.2.11 of nydus snapshotter.
Fix it to use the latest available version (v0.13.4) instead.
Fixes #211
> nydus-snapshotter: fix snapshotter version in README

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: change structure of the metrics config in client

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
According to the container documentation, the registry host namespace should include a port. I have also tested this in practice; the `hosts.toml` configuration under the `certs.d/127.0.0.1` directory indeed does not affect `crictl pull 127.0.0.1:5000/xxx`. Therefore, you should create a `certs.d/127.0.0.1:5000` directory.
https://github.com/containerd/containerd/blob/main/docs/hosts.md#registry-host-namespace
Solve the issue of invalid mirror for registry with port.
> fix: the registry host namespace should include the port

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: optimize scheduler default config

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
when runtime is crio，helm-charts can't start dfdaemon initcontainer with 
```yaml
containerRuntime:
crio:
enable: true
injectConfigPath: true
```
> crio adaptation

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/client/podmonitor.yaml
- charts/dragonfly/templates/dfdaemon/podmonitor.yaml
> fix: spec.podMetricsEndpoints.port need to be string

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/client/client-daemonset.yaml
- charts/dragonfly/templates/manager/manager-deployment.yaml
- charts/dragonfly/templates/scheduler/scheduler-statefulset.yaml
- charts/dragonfly/templates/seed-client/seed-client-statefulset.yaml
The PriorityClass setting is not working as expected because the cluster is running EKS version 1.28, where the scheduling.k8s.io/v1beta1 API version has been deprecated. Currently, the chart is checking for scheduling.k8s.io/v1beta1, which is causing issues. This problem is evident in the Helm chart file at [client-daemonset.yaml#L63](https://github.com/dragonflyoss/helm-charts/blob/main/charts/dragonfly/templates/client/client-daemonset.yaml#L63).
As of Kubernetes v1.22, the scheduling.k8s.io/v1beta1 API version for PriorityClass is no longer served. Consequently, the priorityclassname configuration is not being applied correctly.
Reference:
For more information, refer to the [Kubernetes deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#priorityclass-v1 …
> Removed the condition validation with scheduling.k8s.io/v1beta1 when applying Priorityclassname

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
The default value of `hostGCInterval` has been modified to `5m` in the Dragonfly2 main project, now synchronize this modification to the helm chart.
https://github.com/dragonflyoss/Dragonfly2/issues/3523
> feat: reduce host gc interval to clear offline peers' metadata in time

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/manager/manager-svc.yaml
- charts/dragonfly/templates/scheduler/scheduler-svc.yaml
- charts/dragonfly/templates/seed-client/seed-client-svc.yaml
- charts/dragonfly/values.yaml
Add `nodePort` for scheduler, manager and seed-client services, so that nodePort can be configured when the service type is `nodePort`.
https://github.com/dragonflyoss/Dragonfly2/issues/3523
> feat: add nodePort for services

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request involves updates to the Dragonfly Helm chart, specifically focusing on the version bump and changes to the cache size configuration. The most important changes include updating the chart version, modifying the LFU cache size, and updating related documentation.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6): Updated the chart version from `1.2.27` to `1.2.28`.
Cache configuration changes:
* [`charts/dragonfly/values.yaml`](diffhunk://#diff-e11a1bce6de1a9204ff3555f83b37165f2b1694c9d2073422a40daf6f8e9d63bL180-R180): Changed the LFU cache size from `200000` to `50000`.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L30 …
> feat: change LFU size to 50000 in manager cache

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request includes several updates to the Dragonfly Helm chart, primarily focusing on configuration changes to the manager cache and job garbage collection (GC) settings. The most important changes are summarized below:
* Updated the chart version from `1.2.28` to `1.2.29` in `charts/dragonfly/Chart.yaml`.
* Changed the LFU cache size from `50000` to `30000` in `charts/dragonfly/Chart.yaml`, `charts/dragonfly/README.md`, and `charts/dragonfly/values.yaml` [[1]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L30-R31) [[2]](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f07d262cb7cda2783bL247-R254) [[3]](diffhunk://#diff-e11a1bce6de1a9204ff3555f83b37165f2b1694c9d2073422a40daf6f8e9d63bL180-R180).
* Updated the job GC interval from …
> feat: change job and cache config for manager

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/client/client-daemonset.yaml
we missed the mount config for runtime: ```docker``` and ```podman```. Without the mount, the dfinit is not able to apply the modification on the host.
https://github.com/dragonflyoss/dragonfly/issues/3745
> add mount config for docker and podman volume

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/client/client-daemonset.yaml
This pull request includes updates to the `dragonfly` chart to add support for exporting a Unix domain socket (UDS) to the host, along with a version bump for the chart.
Key changes include:
* **Version Update:**
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6): Updated the chart version from `1.3.2` to `1.3.3`.
* **Annotations Update:**
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L30-R30): Updated the `artifacthub.io/changes` annotation to reflect the new feature of exporting a Unix domain socket (UDS) to the host.
* **Template Update:**
* [`charts/dragonfly/templates/client/client-daemonset.yaml`](diffhunk://#diff-8cf66934693161309da9877cfb771789 …
> feat: export unix domain socket(UDS) to host

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/client/client-daemonset.yaml
This pull request includes updates to the Dragonfly Helm chart to improve volume mounts and update the version. The most important changes include updating the version number, optimizing volume mounts for the Unix domain socket, and reordering the `volumeMounts` entries for clarity.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6): Updated the chart version from `1.3.3` to `1.3.4`.
Optimizations and reordering:
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L30-R30): Updated the `artifacthub.io/changes` annotation to reflect the optimization of volumes and volumeMounts for the Unix domain socket.
* …
> feat: optimize volumes and volumeMounts for unix domain socket(UDS)

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request includes several updates to the Dragonfly Helm chart, primarily focusing on version upgrades for various components. The most important changes include updating the version of the chart itself, as well as updating the image tags for the client, seed-client, and dfinit components.
Version upgrades:
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6): Updated the chart version from `1.3.4` to `1.3.5` and the client image version to `0.2.2`. [[1]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6) [[2]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L30-R30) [[3]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9 …
> feat: update client version to 0.2.4

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request includes updates to the Dragonfly Helm chart to address issues with volume mounts and to update the version. The most important changes are related to modifying the volume configuration and updating the version number.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6): Updated the chart version from `1.3.7` to `1.3.8`.
Volume configuration changes:
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L30-R30): Updated the `artifacthub.io/changes` annotation to reflect the use of `emptyDir` for the DaemonSet instead of `hostPath`.
* [`charts/dragonfly/README.md`](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200 …
> feat: use emptyDir for the DaemonSet to avoid issues associated with volume mounts using hostPath

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/manager/manager-svc.yaml
- charts/dragonfly/templates/scheduler/scheduler-svc.yaml
Dragonfly is not working with Istio (sidecar injection). The scheduler fails to start as it seems like it can't connect to other components with gRPC calls. This prevents all other components from running.
Istio selects the wrong protocol. We can fix that by adding appProtocol: grpc to the Dragonfly services. More info here: https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/
https://github.com/dragonflyoss/helm-charts/issues/350
It adds support for Istio mesh.
> fix: specify protocol for grpc services to instruct Istio

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/client/client-daemonset.yaml
This pull request includes updates to the `charts/dragonfly/Chart.yaml` file. The changes involve updating the version of the Dragonfly chart and correcting the annotations related to the client-daemonset.yaml file.
* Updated the `version` field from `1.3.15` to `1.3.16` to reflect the latest release.
Annotations correction:
* Modified the `artifacthub.io/changes` annotation to correct the description of changes, specifically fixing the indentation in the `client-daemonset.yaml` file.
> fix: correct indentation in client-daemonset.yaml hostPath

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request includes several updates to the `dragonfly` Helm chart, focusing on version upgrades for various components. The most important changes include updating the versions of the `dragonfly` chart, client, manager, scheduler, and seed-client images.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6): Updated the `dragonfly` chart version from `1.3.16` to `1.3.18` and the client version annotation to `v0.2.23`. [[1]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6) [[2]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L30-R30)
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e1427874 …
> chore: bump client to v0.2.23

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/values.yaml
This pull request introduces updates to the Dragonfly Helm chart, focusing on adding support for Redis Sentinel authentication and updating the chart version. The most significant changes include the addition of new fields for Redis Sentinel credentials, updates to configuration templates, and the version bump in the chart metadata.
* Added `sentinelUsername` and `sentinelPassword` fields to `externalRedis` in `values.yaml` to support Redis Sentinel authentication.
* Updated `manager-configmap.yaml` and `scheduler-configmap.yaml` to include the new `sentinelUsername` and `sentinelPassword` fields in the configuration templates. [[1]](diffhunk://#diff-951b3103fd9d8a55ee0c45f002b625eeffcad463a83a5a3bdc0ca6c398c5ec80R62-R63) [[2]](diffhunk://#diff-c05eaf561a55a7c637819cee107deb97d578c5304e869 …
> feat(externalRedis): add sentinel username and password fields

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request updates the Dragonfly Helm chart to include a version bump and modifies the scheduler's `peerTTL` configuration to significantly extend its time-to-live. Below is a summary of the most important changes grouped by theme.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6): Updated the chart version from `1.3.34` to `1.3.35`.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L30-R30): Updated the `artifacthub.io/changes` annotation to reflect the change of `peerTTL` from `48h` to `720h`.
* [`charts/dragonfly/README.md`](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f07d262cb7cda2783bL365-R365): Updated the `peerTTL` …
> feat: change peerTTL from 48h to 720h in scheduler

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request updates the Dragonfly Helm chart to include new versions of its components and introduces support for OpenTelemetry (OTel) tracing protocols. The most significant changes involve version bumps for various components and the addition of tracing configurations.
* Updated `version` to `1.3.37` and `appVersion` to `2.2.4-rc.0` in `charts/dragonfly/Chart.yaml`.
* Updated image tags for `manager`, `scheduler`, `client`, `seed-client`, and `dfinit` components to align with the new release versions in `charts/dragonfly/Chart.yaml`, `charts/dragonfly/README.md`, and `charts/dragonfly/values.yaml`. [[1]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L41-R51) [[2]](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f07d262cb7cda2783bL18 …
> feat: update Dragonfly Helm chart to v1.3.37 with OTLP HTTP/GRPC support

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/values.yaml
This pull request introduces several updates to the Dragonfly Helm chart, including new configuration options, cleanup of deprecated settings, and documentation updates. The changes focus on enhancing configurability, improving logging granularity, and streamlining options for the manager, scheduler, and client components.
* Added `logLevel` configuration for both `manager` and `scheduler` to specify logging levels such as "debug", "info", "warn", etc. [[1]](diffhunk://#diff-951b3103fd9d8a55ee0c45f002b625eeffcad463a83a5a3bdc0ca6c398c5ec80R28) [[2]](diffhunk://#diff-e11a1bce6de1a9204ff3555f83b37165f2b1694c9d2073422a40daf6f8e9d63bR156-R159) [[3]](diffhunk://#diff-e11a1bce6de1a9204ff3555f83b37165f2b1694c9d2073422a40daf6f8e9d63bR420-R423)
* Introduced `collectedPieceTimeout` for `client` and …
> feat: Added collectedPieceTimeout option for dfdaemon and seedClient (default: 10s)

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request updates the Dragonfly Helm chart to use newer versions of several images and components. The changes primarily involve bumping the image tags for `client`, `seed-client`, and `dfinit` from `v1.0.0` to `v1.0.1`, along with corresponding updates in the documentation and configuration files.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6): Updated the chart version from `1.4.0` to `1.4.1` and bumped the `client` image version from `v1.0.0` to `v1.0.1` in the annotations section. [[1]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6) [[2]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L30-R30)
* …
> chore: bump client to v1.0.1

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request updates the Dragonfly Helm chart to use the latest `v1.0.12` versions of the client and dfinit images, replacing the previous `v1.0.11` versions. It also updates related documentation and metadata to reflect these changes.
**Image version updates:**
* Updated the `client`, `seed-client`, and `dfinit` image tags from `v1.0.11` to `v1.0.12` in `charts/dragonfly/Chart.yaml` and `charts/dragonfly/values.yaml`. [[1]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L46-R49) [[2]](diffhunk://#diff-e11a1bce6de1a9204ff3555f83b37165f2b1694c9d2073422a40daf6f8e9d63bL705-R705) [[3]](diffhunk://#diff-e11a1bce6de1a9204ff3555f83b37165f2b1694c9d2073422a40daf6f8e9d63bL1132-R1132) [[4]](diffhunk://#diff-e11a1bce6de1a9204ff3555f83b37165f2b1694c9d2073422a40daf …
> chore: bump client to v1.0.12
