dragonflyoss/helm-charts

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
> chore: bugfix for dns policy and ca path

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update image version

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> fix: docker hub source address

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/cdn/cdn-statefulset.yaml
- charts/dragonfly/templates/manager/manager-deployment.yaml
- charts/dragonfly/templates/scheduler/scheduler-statefulset.yaml
- charts/dragonfly/values.yaml
> feat: custom wait for initcontainer

- README.md
- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/README.md.gotmpl
- charts/dragonfly/values.yaml
> docs: update documents

- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
- charts/dragonfly/values.yaml
> feat: manager support multi addresses

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update image verison

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update image version to v2.0.1

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/cdn/cdn-configmap.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/values.yaml
> feat: support custom directory configuration

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
- charts/dragonfly/values.yaml
> feat: add dfdaemon data dir

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/values.yaml
> feat: support for refactored scheduler configuration

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: change peer and task ttl

- charts/dragonfly/templates/cdn/cdn-configmap.yaml
Signed-off-by: 孙伟鹏 <weipeng.swp@alibaba-inc.com>
> CDN manager config

- charts/dragonfly/Chart.yaml
- charts/dragonfly/values.yaml
> feat: dynconfig type is deprecated

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: change scheduler retry limit

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: change scheduler retry interval

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update scheduler listen limit default value

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/cdn/cdn-configmap.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/values.yaml
> feat: add pprof console and verbose configuration

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: add scheduler retryBackSourceLimit config

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
- charts/dragonfly/values.yaml
> chore: add dfdaemon metrics config

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update image tag to v2.0.2-rc.4

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update image tag

- .github/workflows/lint-test.yml
- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/README.md.gotmpl
> chore: docs validate

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/values.yaml
> feat: scheduler blocks cdn

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/README.md.gotmpl
> fix: artifacthub badge

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/values.yaml
> feat: scheduler remove listenLimit config

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/README.md.gotmpl
- charts/dragonfly/templates/NOTES.txt
- charts/dragonfly/values.yaml
> feat: update dragonfly image tag to v2.0.2

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/README.md.gotmpl
- charts/dragonfly/templates/_helpers.tpl
- charts/dragonfly/templates/cdn/cdn-configmap.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/templates/seed-peer/metrics-svc.yaml
- charts/dragonfly/templates/seed-peer/prometheusrule.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-configmap.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-statefulset.yaml
- charts/dragonfly/templates/seed-peer/servicemonitor.yaml
- charts/dragonfly/values.yaml
> feat: add seed peer logic

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/cdn/cdn-statefulset.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
- charts/dragonfly/templates/jaeger/jaeger-deployment.yaml
- charts/dragonfly/templates/manager/manager-deployment.yaml
- charts/dragonfly/templates/scheduler/scheduler-statefulset.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-statefulset.yaml
Signed-off-by: czomo <tomaszjdul@gmail.com>
Following helm good practices I've added automatically roll deployments. It helps to have updated config after changing configuration inside configmap.
See for more details https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
> Automatically roll releases

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
- charts/dragonfly/templates/manager/manager-ingress.yaml
Signed-off-by: czomo <tomaszjdul@gmail.com>
I've made a mistake(my bad) in https://github.com/dragonflyoss/helm-charts/pull/73 and config doesn't work the way we need. I modified it to be able to fetch the values  from values.yaml. Right now it always stays the same - the default one `config.toml`.
> Patch pull request #73 - config.toml

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update dragonfly image version to v2.0.3

- README.md
- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/README.md.gotmpl
> docs: add prerequisites to installation

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-configmap.yaml
- charts/dragonfly/values.yaml
> feat: add object storage to manager and dfdaemon

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/seed-peer/seed-peer-configmap.yaml
- charts/dragonfly/values.yaml
> feat: add filter to object storage configuration

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: add maxReplicas to object storage configuration

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-statefulset.yaml
> feat: object storage add container port

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: change local cache ttl

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/values.yaml
> feat: scheduler adds dataDir configuration

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-configmap.yaml
- charts/dragonfly/values.yaml
> feat: dfdaemon adds defaultTag configuration

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-configmap.yaml
- charts/dragonfly/values.yaml
> feat: health config

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> fix: dfdaemon default value of download unix socket

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: dfdaemon removes default value of workhome

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/values.yaml
> feat: scheduler adds workHome configuration

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update dragonfly image version to v2.0.5

- charts/dragonfly/templates/manager/servicemonitor.yaml
- charts/dragonfly/templates/scheduler/servicemonitor.yaml
- charts/dragonfly/templates/seed-peer/servicemonitor.yaml
Signed-off-by: Yiyang Huang <huangyiyang499@gmail.com>
> fix: servicemonitor selector match labels

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
Fix issue reported by leonids:
```
sed: can't move '/etc/hostsEDEofM' to '/etc/hosts': Resource busy
```
> chore: update dfdaemon post start

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-configmap.yaml
- charts/dragonfly/values.yaml
> feat: add security config

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> chore: update dragonfly image verison to v2.0.6

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: change peer rate limt configuration

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/values.yaml
> feat: update iamge version to v2.0.7-alpha.2

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-configmap.yaml
- charts/dragonfly/values.yaml
> feat: remove listenIP and advertiseIP field from dfdaemon

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: add prefetch fields to dfdaemon config

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: remove host and task ttl

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
- charts/dragonfly/values.yaml
> feat: add fallback mirror to containerd

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update image version to v2.0.7

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-configmap.yaml
- charts/dragonfly/values.yaml
> feat: update image version to v2.0.8-alpha.4

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
> fix: matching directory of docker.service systemd

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-configmap.yaml
- charts/dragonfly/values.yaml
> feat: add announcer to dfdaemon

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/values.yaml
> feat: add storage configuration to scheduler

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> chore: release v2.0.8

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: add the timout of downloading piece to scheduler

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/README.md.gotmpl
- charts/dragonfly/values.yaml
> docs: update externalRedis and update image tag

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: add ipAddresses and dnsNames to certSpec

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
> chore: update charts dependencies version

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update image version to v2.0.9-alpha.7

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
https://github.com/dragonflyoss/Dragonfly2/issues/1972
> feat: add S3ForcePathStyle to manager configuration

- charts/nydus-snapshotter/Chart.yaml
- charts/nydus-snapshotter/README.md
- charts/nydus-snapshotter/templates/nydus-snapshotter/snapshotter-daemonset.yaml
- charts/nydus-snapshotter/values.yaml
Signed-off-by: bin liu <liubin0329@gmail.com>
> add `args` to customize container start command

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/templates/scheduler/scheduler-svc.yaml
- charts/dragonfly/values.yaml
> feat: add wait-for-scheduler initContainer to dfdaemon

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: remove netTopology from configuration

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update dragonfly image version

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/release.yml
> chore: update issue template

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: add host ttl to scheduler configuration

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
- charts/dragonfly/values.yaml
feat: dfdaemon support set scheduler.netAddr
https://github.com/dragonflyoss/helm-charts/issues/155
> feat: dfdaemon support set scheduler.netAddr

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
- charts/dragonfly/templates/manager/manager-deployment.yaml
- charts/dragonfly/templates/scheduler/scheduler-statefulset.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-statefulset.yaml
- charts/dragonfly/values.yaml
- Services support to set imagePullSecrets.
> feat: service supports to set imagePullSecrets

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
- Fix wait-for-scheduler init container in dfdaemon and hostPID field in dfdaemon.
> fix: wait-for-scheduler init container in dfdaemon and hostPID field in dfdaemon

- charts/nydus-snapshotter/Chart.yaml
- charts/nydus-snapshotter/README.md
- charts/nydus-snapshotter/templates/nydus-snapshotter/snapshotter-configmap.yaml
- charts/nydus-snapshotter/values.yaml
Signed-off-by: bin liu <liubin0329@gmail.com>
> feat: change mirrorConfig of dragonfly to array

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/values.yaml
- Add auth config to manager.
https://github.com/dragonflyoss/Dragonfly2/security/advisories/GHSA-hpc8-7wpm-889w
> feat: add auth config to manager

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
- Update image version to `v2.0.9`.
> chore: update image version to v2.0.9

- charts/nydus-snapshotter/Chart.yaml
- charts/nydus-snapshotter/README.md
- charts/nydus-snapshotter/templates/nydus-snapshotter/snapshotter-configmap.yaml
- charts/nydus-snapshotter/values.yaml
1. Update nydus-snapshotter to 0.6.1.
2. Fix outdated config files.
> feat: update nydus-snapshotter to 0.6.1

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/values.yaml
> feat: add advertiseIP and advertisePort

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
- Change default value of TTL in manager cache.
- Change default value of size in manager cache.
> feat: change default value of TTL in manager cache

- INSTALL.md
- README.md
- Optimize `INSTALL.md` and `README.md`.
> docs: optimize INSTALL.md and README.md

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
- Remove security domain in configuration.
> feat: remove security domain in configuration

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/values.yaml
> feat: update image version to v2.1.0-alpha.6

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
- charts/dragonfly/values.yaml
> chore: modify comment

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update image verison to v2.1.0

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/values.yaml
> feat: add tls config to manager rest server

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/values.yaml
> feat: add tls config to preheat in manager

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
修改 busybox:latest 的镜像拉取策略， 防止非常旧的版本存在导致nc命令异常
> chore: update busybox:latest pullPolicy: Always

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update image tag to v2.1.10

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
- charts/dragonfly/values.yaml
> fix: incorrect dockerhub domain being injected when using containerd config_path

- charts/nydus-snapshotter/Chart.yaml
- charts/nydus-snapshotter/README.md
- charts/nydus-snapshotter/values.yaml
Update nydus-snapshotter to 0.9.0.
> feat: update nydus-snapshotter to 0.9.0

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
- charts/nydus-snapshotter/Chart.yaml
> feat: add sync peers configuration and change maintainers

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
- charts/dragonfly/templates/manager/manager-deployment.yaml
- charts/dragonfly/templates/scheduler/scheduler-statefulset.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-statefulset.yaml
- charts/dragonfly/templates/trainer/trainer-deployment.yaml
- charts/dragonfly/templates/triton/triton-deployment.yaml
- charts/dragonfly/values.yaml
> feat: add maxProcs to service

- README.md
+ fix: broken link of the nydus helm chart document
> fix: broken link of the nydus helm chart document

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/client/client-configmap.yaml
- charts/dragonfly/templates/client/client-daemonset.yaml
- charts/dragonfly/templates/seed-client/seed-client-configmap.yaml
- charts/dragonfly/values.yaml
> fix: manager addrs is empty in client and seed client

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/client/client-configmap.yaml
- charts/dragonfly/templates/seed-client/seed-client-configmap.yaml
- charts/dragonfly/values.yaml
> fix: empty host and empty tracing in client config

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/client/client-configmap.yaml
- charts/dragonfly/templates/seed-client/seed-client-configmap.yaml
> feat: add protocol to manager address for client

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: change default value of announceInterval

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/client/client-daemonset.yaml
- charts/dragonfly/templates/seed-client/seed-client-statefulset.yaml
- charts/dragonfly/values.yaml
> feat: add verbose args to client command

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: change default value of the retry config

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: change default value of refresh interval in dynconfig

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: change default value of announce interval in dynconfig

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/client/client-daemonset.yaml
- charts/dragonfly/templates/seed-client/seed-client-statefulset.yaml
- charts/dragonfly/values.yaml
> feat: add log level argument to client

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/values.yaml
> feat: remove advertisePort in manager config

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: change default value of retry in scheduler

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
- charts/dragonfly/values.yaml
add updateStrategy support for dfdaemon
> feat: add updateStrategy support for dfdaemon

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/client/client-daemonset.yaml
- charts/dragonfly/templates/manager/manager-deployment.yaml
- charts/dragonfly/templates/scheduler/scheduler-statefulset.yaml
- charts/dragonfly/templates/seed-client/seed-client-statefulset.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-statefulset.yaml
- charts/dragonfly/templates/trainer/trainer-deployment.yaml
- charts/dragonfly/values.yaml
> feat: add updateStrategy to client, manager, scheduler, seed-client and seed-peer

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
Fix  dfdaemon restart check config issue
> Fix  dfdaemon restart check config issue

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> update d7y values comments

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/_helpers.tpl
- charts/dragonfly/templates/client/client-daemonset.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
- charts/dragonfly/templates/manager/manager-deployment.yaml
- charts/dragonfly/templates/scheduler/scheduler-statefulset.yaml
- charts/dragonfly/templates/seed-client/seed-client-statefulset.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-statefulset.yaml
- charts/dragonfly/templates/trainer/trainer-deployment.yaml
- charts/dragonfly/templates/triton/triton-deployment.yaml
- charts/dragonfly/values.yaml
> feat: rewrite image and add global.imageRegistry

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/client/client-daemonset.yaml
- charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
- charts/dragonfly/templates/manager/manager-deployment.yaml
- charts/dragonfly/templates/scheduler/scheduler-statefulset.yaml
- charts/dragonfly/templates/seed-client/seed-client-statefulset.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-statefulset.yaml
- charts/dragonfly/templates/trainer/trainer-deployment.yaml
- charts/dragonfly/values.yaml
> feat: add global.nodeSelector for config

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: remove replicas field in client daemonset

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/_helpers.tpl
- charts/dragonfly/templates/client/client-daemonset.yaml
- charts/dragonfly/templates/seed-client/seed-client-statefulset.yaml
- charts/dragonfly/templates/seed-peer/seed-peer-statefulset.yaml
- charts/dragonfly/values.yaml
> feat: add global.storageClass to configure the storage class for PVCs

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/seed-client/seed-client-statefulset.yaml
- charts/dragonfly/templates/seed-client/seed-client-svc.yaml
- charts/dragonfly/values.yaml
> feat: add service for seed client

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/client/client-configmap.yaml
- charts/dragonfly/templates/seed-client/seed-client-configmap.yaml
> fix: addrs config for seed client

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/seed-peer/seed-peer-statefulset.yaml
- charts/dragonfly/values.yaml
> add hostNetwork for sedd-peer

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/triton/triton-deployment.yaml
- charts/dragonfly/values.yaml
> feat: add configure for triton

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> chore: update image verison

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: add client config for charts

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update client version to v0.1.37

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/client/client-configmap.yaml
- charts/dragonfly/templates/seed-client/seed-client-configmap.yaml
- charts/dragonfly/values.yaml
> feat: add health config for client and update image version

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: set calculateDigest to false in dfdaemon, because it has bug in large files

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/client/client-configmap.yaml
- charts/dragonfly/templates/client/client-daemonset.yaml
- charts/dragonfly/templates/seed-client/seed-client-configmap.yaml
- charts/dragonfly/templates/seed-client/seed-client-statefulset.yaml
- charts/dragonfly/templates/seed-client/seed-client-svc.yaml
- charts/dragonfly/values.yaml
> feat: add stats config for dfdaemon

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: add buffer size for client

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/client/podmonitor.yaml
- charts/dragonfly/templates/seed-client/metrics-svc.yaml
> feat: fix metric port for monitor

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: optimize default params for concurrent downloading

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update image version and change default value of storage keep

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> chore: update image tag

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/templates/manager/manager-deployment.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
> feat: Use headless service for redis

- charts/nydus-snapshotter/Chart.yaml
- charts/nydus-snapshotter/README.md
- charts/nydus-snapshotter/templates/_helpers.tpl
- charts/nydus-snapshotter/templates/nydus-snapshotter/snapshotter-daemonset.yaml
- charts/nydus-snapshotter/values.yaml
> feat: add global config for nydus-snapshotter

- .github/workflows/release.yml
- README.md
- charts/dragonfly-stack/.helmignore
- charts/dragonfly-stack/Chart.yaml
- charts/dragonfly-stack/README.md
- charts/dragonfly-stack/README.md.gotmpl
- charts/dragonfly-stack/values.yaml
- charts/nydus-snapshotter/Chart.yaml
- charts/nydus-snapshotter/README.md
- charts/nydus-snapshotter/values.yaml
> feat: add dragonfly-stack charts

- .github/workflows/lint-test.yml
- charts/dragonfly-stack/Chart.yaml
- charts/dragonfly-stack/README.md
- charts/dragonfly-stack/values.yaml
> feat: update nydus-snapshotter version in dragonfly-stack

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/templates/manager/manager-deployment.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
> feat: use master service for redis

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/client/client-daemonset.yaml
- charts/dragonfly/templates/manager/manager-deployment.yaml
- charts/dragonfly/templates/scheduler/scheduler-statefulset.yaml
- charts/dragonfly/templates/seed-client/seed-client-statefulset.yaml
- charts/dragonfly/values.yaml
> feat: add resources config for initContainer

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
> feat: update dependencies version

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/_helpers.tpl
- charts/dragonfly/templates/client/client-configmap.yaml
- charts/dragonfly/templates/client/client-daemonset.yaml
- charts/dragonfly/templates/client/dfinit-configmap.yaml
- charts/dragonfly/templates/client/metrics-svc.yaml
- charts/dragonfly/templates/client/prometheusrule.yaml
- charts/dragonfly/templates/client/servicemonitor.yaml
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/templates/manager/manager-deployment.yaml
- charts/dragonfly/templates/manager/manager-ingress.yaml
- charts/dragonfly/templates/manager/manager-svc.yaml
- charts/dragonfly/templates/manager/metrics-svc.yaml
- charts/dragonfly/templates/manager/prometheusrule.yaml
- charts/dragonfly/templates/manager/servicemonitor.yaml
- charts/dragonfly/templates/scheduler/metrics-svc.yaml
- charts/dragonfly/templates/scheduler/prometheusrule.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/templates/scheduler/scheduler-statefulset.yaml
- charts/dragonfly/templates/scheduler/scheduler-svc.yaml
- charts/dragonfly/templates/scheduler/servicemonitor.yaml
- charts/dragonfly/templates/seed-client/metrics-svc.yaml
- charts/dragonfly/templates/seed-client/prometheusrule.yaml
- charts/dragonfly/templates/seed-client/seed-client-configmap.yaml
- charts/dragonfly/templates/seed-client/seed-client-statefulset.yaml
- charts/dragonfly/templates/seed-client/seed-client-svc.yaml
- charts/dragonfly/templates/seed-client/servicemonitor.yaml
- charts/dragonfly/values.yaml
> feat: add namespaceOverride to support install in different namespace

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/client/client-daemonset.yaml
- charts/dragonfly/templates/seed-client/seed-client-statefulset.yaml
- charts/dragonfly/values.yaml
> feat: change readinessProbe and livenessProbe for client and seed-client

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/client/client-daemonset.yaml
- charts/dragonfly/templates/seed-client/seed-client-statefulset.yaml
> feat: change probe timeout for client

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/client/client-daemonset.yaml
- charts/dragonfly/templates/seed-client/seed-client-statefulset.yaml
- charts/dragonfly/values.yaml
> feat: update client image version to v0.1.86

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
[#3377
](https://github.com/dragonflyoss/Dragonfly2/issues/3377)
> feat: print the logs to the console when service is started

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: change rateLimit to human readable format in client

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update image tag for client

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> chore: update client image and Dragonfly image

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update client version to v0.1.103

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: add ratelimit for job in manager

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: change capacity and quantum for manager job

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> chore: update image version

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: add disableShared for client to disable shared data with other peers

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: add gc config for manager job

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: add insecureSkipVerify and tlsConfig for preheating in the manager

- charts/dragonfly-stack/README.md
- charts/dragonfly-stack/values.yaml
- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/values.yaml
> feat: remove network topology config

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/client/client-configmap.yaml
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/templates/seed-client/seed-client-configmap.yaml
- charts/dragonfly/values.yaml
> feat: add self-signed certs config

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: add basic auth configuration for dfdaemon

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: add prefetch comment for dfdaemon and update client image

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: update image version to v2.1.62

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request includes updates to the Dragonfly Helm chart to upgrade the versions of various components and images. The changes ensure that the chart uses the latest versions of Dragonfly and its dependencies.
* Updated `version` to 1.2.23 and `appVersion` to 2.1.64 in `charts/dragonfly/Chart.yaml`.
* Updated the Dragonfly version to 2.1.64 and client version to 0.1.118 in the `artifacthub.io/changes` annotation.
Image tag updates:
* Updated image tags for `manager`, `scheduler`, `client`, `seed-client`, and `dfinit` in `charts/dragonfly/Chart.yaml`.
* Updated image tags for `client.dfinit.image.tag`, `client.image.tag`, `manager.image.tag`, `scheduler.image.tag`, and `seedClient.image.tag` in `charts/dragonfly/README.md`. …
> feat: update client and dragonfly version

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> feat: add prefetch rate limit configuration

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
> chore: update client version to 0.1.125

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request includes several updates to the Dragonfly Helm chart, primarily focusing on updating the versions of various components and their corresponding image tags.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R7): Updated the chart version to 1.3.0 and the application version to 2.2.0.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L42-R50): Updated the manager, scheduler, client, and dfinit image versions to 2.2.0 and 0.2.0 respectively.
Documentation updates:
* [`charts/dragonfly/README.md`](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f07d262cb7cda2783bL177-R177): Updated image tag references for …
> feat: update dragonfly version to 2.2.0

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request includes updates to the Dragonfly Helm chart, primarily focusing on version updates for various components. The changes ensure that the chart uses the latest versions of the Dragonfly components.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6): Updated the chart version to `1.3.1` and the client version in annotations to `0.2.1`. [[1]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6) [[2]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L30-R30)
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L46-R49): Updated the image tags for `client`, …
> feat: update client version to 0.2.1

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request includes updates to the Dragonfly Helm chart, primarily updating the version numbers of various images and the application itself.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R7): Updated `version` to `1.3.6` and `appVersion` to `2.2.1-rc.0`.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L30-R31): Updated annotations to reflect the new Dragonfly version `2.2.1-rc.0` and client version `0.2.9`.
Image tag updates:
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L41-R50): Updated image tags for `manager`, `scheduler`, `client`, `seed-client`, and …
> feat: update dragonfly version to 2.2.1-rc.0

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request includes several updates to the `charts/dragonfly` Helm chart, primarily focusing on version upgrades for various images and dependencies.
Version upgrades:
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6): Updated the chart version from `1.3.6` to `1.3.7` and the client version from `0.2.9` to `0.2.11`. [[1]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6) [[2]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L30-R30)
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L46-R49): Updated the image tags for `client`, `seed-client`, and `dfinit` from `v0.2.9` to …
> feat: bump client from v0.2.9 to v0.2.11

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request includes several updates to the Dragonfly Helm chart, primarily focused on adding request rate limits for the gRPC server and updating the chart version. The most important changes are summarized below:
* Updated the chart version from `1.3.8` to `1.3.9` in `charts/dragonfly/Chart.yaml`.
* Added a request rate limit for the client's gRPC server in `charts/dragonfly/Chart.yaml`.
* Added `requestRateLimit` configuration entries for download and upload gRPC servers in `charts/dragonfly/README.md`. [[1]](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f07d262cb7cda2783bR134) [[2]](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f07d262cb7cda2783bR167) [[3]](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f07d262cb7cda2783bR439) …
> feat: add request rate limit for client's grpc server

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/client/client-daemonset.yaml
- charts/dragonfly/templates/manager/manager-deployment.yaml
- charts/dragonfly/templates/scheduler/scheduler-statefulset.yaml
- charts/dragonfly/templates/seed-client/seed-client-statefulset.yaml
- charts/dragonfly/values.yaml
This pull request updates the Dragonfly Helm chart to use newer versions of the Dragonfly components. The changes include updating the version numbers and image tags in multiple files, ensuring the chart uses the latest releases.
Version and image tag updates:
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R7): Updated `version` to `1.3.10` and `appVersion` to `2.2.1-rc.2`.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L30-R31): Updated annotations to reflect new client and Dragonfly versions.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L41-R50): Updated image tags for `manager`, …
> chore: update dragonfly and client version

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/client/metrics-svc.yaml
- charts/dragonfly/templates/manager/manager-svc.yaml
- charts/dragonfly/templates/manager/metrics-svc.yaml
- charts/dragonfly/templates/scheduler/metrics-svc.yaml
- charts/dragonfly/templates/scheduler/scheduler-svc.yaml
- charts/dragonfly/templates/seed-client/metrics-svc.yaml
- charts/dragonfly/templates/seed-client/seed-client-svc.yaml
- charts/dragonfly/values.yaml
This pull request includes updates to the Dragonfly Helm chart, primarily focusing on version updates and port changes.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6): Updated the chart version from `1.3.11` to `1.3.12`.
Port changes:
* [`charts/dragonfly/README.md`](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f07d262cb7cda2783bL438-R449): Updated various server ports for health, metrics, proxy, stats, and upload servers in the seed client configuration. [[1]](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f07d262cb7cda2783bL438-R449) [[2]](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f07d262cb7cda2783bL459-R465)
* …
> feat: change service ports in seed client

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request includes updates to the Dragonfly Helm chart, focusing on updating version numbers and image tags to the latest stable releases.
Key updates:
*Version updates:*
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R7): Updated `version` to `1.3.15` and `appVersion` to `2.2.1`.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L30-R31): Updated annotations to reflect new versions: Dragonfly `2.2.1` and client `0.2.19`.
*Image tag updates:*
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L41-R50): Updated image tags for manager, scheduler, client, and seed-client to their latest …
> feat: update client to 0.2.19 and dragonfly to 2.2.1

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request includes several updates to the Dragonfly Helm chart, primarily focusing on updating the client version and associated tags to ensure the latest version is used.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6): Updated the chart version from `1.3.16` to `1.3.17`.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L30-R30): Updated the client version to `v0.2.22` in the annotations.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L45-R49): Updated the image tags for `client`, `seed-client`, and `dfinit` to `v0.2.22`.
Documentation updates:
* …
> chore: bump client verison to 0.2.22

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request updates the Dragonfly Helm chart to incorporate the latest client and related components (e.g., `dfinit`, `seed-client`) with version `v0.2.24`. The changes ensure consistency across the chart's metadata, configuration, and documentation.
* Updated the chart version to `1.3.20` in `charts/dragonfly/Chart.yaml` to reflect the new release.
* Updated the client image version and related components (`client`, `seed-client`, `dfinit`) from `v0.2.23` to `v0.2.24` in `Chart.yaml`, `values.yaml`, and `README.md`. [[1]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L45-R49) [[2]](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f07d262cb7cda2783bL179-R179) [[3]](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f07d262c …
> chore: bump client to v0.2.24

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request updates the Dragonfly Helm chart to improve version consistency, enhance configuration options, and refine documentation. The most notable changes include updating the application and image versions, introducing a rolling update strategy for the client daemonset, and reflecting these updates in the chart's documentation.
* Updated `version` to `1.3.21` and `appVersion` to `2.2.2` in `charts/dragonfly/Chart.yaml` to align with the latest release.
* Updated image tags for `manager` and `scheduler` from `v2.2.2-rc.0` to `v2.2.2` in `charts/dragonfly/Chart.yaml`, `charts/dragonfly/README.md`, and `charts/dragonfly/values.yaml`. [[1]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L41-R44) …
> feat: Add updateStrategy for client daemonset

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/client/client-daemonset.yaml
> fix(client-daemonset): update checksum annotations for configmaps

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/client/metrics-svc.yaml
- charts/dragonfly/templates/seed-client/metrics-svc.yaml
> refactor(metrics-svc): simplify metrics service condition

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request updates the Dragonfly Helm chart to incorporate the latest versions of its components and associated metadata. The changes include version bumps for the application and its images, as well as updates to documentation and configuration files to reflect these changes.
* Updated the chart version to `1.3.26` and the application version to `2.2.3-rc.0` in `Chart.yaml`.
* Updated image tags for the `manager`, `scheduler`, `client`, `seed-client`, and `dfinit` components to their respective latest versions (`v2.2.3-rc.0` or `v0.2.26`) in `Chart.yaml`, `values.yaml`, and `README.md`. [[1]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L41-R50) [[2]](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f07d262cb7cda2783bL179-R179) …
> feat: bump dragonfly to v2.2.3-rc.0

- .github/auto_assign.yml
- .github/workflows/Untitled
- .github/workflows/auto-assign.yml
- .github/workflows/pr-labels.yml
- .github/workflows/stale.yml
> chore(.github/workflows): add pr-labels, auto-assign and stale actions

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request updates the Dragonfly Helm chart to incorporate new features, configuration adjustments, and image version upgrades. The changes include updates to the application and component image tags, the addition of a new timeout configuration, and modifications to default timeouts and concurrency settings.
* Updated `manager`, `scheduler`, `client`, `seedClient`, and `dfinit` image tags to newer versions (`v2.2.3-rc.2` for `manager` and `scheduler`, and `v0.2.27` for `client`, `seedClient`, and `dfinit`) in `Chart.yaml`, `README.md`, and `values.yaml`. [[1]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L42-R52) [[2]](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f07d262cb7cda2783bL179-R180) …
> feat: bump dragonfly to v2.2.3-rc.2 and add writePieceTimeout for dfdaemon

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request introduces updates to the Dragonfly Helm chart, focusing on enabling debug logging, pprof, and console logging for both the manager and scheduler components. These changes improve observability and debugging capabilities.
* Updated `verbose` configuration for both manager and scheduler to `true` in `charts/dragonfly/values.yaml`, enabling debug-level logging and pprof. (`[[1]](diffhunk://#diff-e11a1bce6de1a9204ff3555f83b37165f2b1694c9d2073422a40daf6f8e9d63bL223-R223)`, `[[2]](diffhunk://#diff-e11a1bce6de1a9204ff3555f83b37165f2b1694c9d2073422a40daf6f8e9d63bL498-R498)`)
* Modified `README.md` to reflect the change in the default value of `verbose` to `true` for manager and scheduler, ensuring documentation is consistent with the updated configuration. …
> feat: set console to true for mangaer and scheduler

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/templates/client/client-daemonset.yaml
- charts/dragonfly/templates/manager/manager-configmap.yaml
- charts/dragonfly/templates/scheduler/scheduler-configmap.yaml
- charts/dragonfly/templates/seed-client/seed-client-statefulset.yaml
- charts/dragonfly/values.yaml
This pull request includes updates to the Dragonfly Helm chart to improve logging configurations, enhance tracing capabilities, and update image versions. The changes focus on replacing verbose logging with console logging, introducing tracing configurations, and bumping client-related image versions.
* Replaced `verbose` logging with `console` logging across the `client`, `seedClient`, `manager`, and `scheduler` configurations in `values.yaml` and corresponding templates. (`[[1]](diffhunk://#diff-8cf66934693161309da9877cfb771789762f3385911bfbef625d3990182de2f9L90-R91)`, `[[2]](diffhunk://#diff-8cf66934693161309da9877cfb771789762f3385911bfbef625d3990182de2f9L150-R151)`, `[[3]](diffhunk://#diff-6d654bfeacaa663ab0bcb823c3429c8dae1c469d46a9c8d6032ab065b471a1a9L91-R92)`, …
> feat: bump client version to v0.2.31

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request updates the Dragonfly Helm chart to use newer versions of its components and improves documentation to reflect these changes. The most important changes involve version updates for the application and its images across multiple files.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R7): Updated `version` to `1.3.33` and `appVersion` to `2.2.4-beta.1`.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L41-R50): Updated image versions in annotations for `manager`, `scheduler`, `client`, `seed-client`, and `dfinit` to match the new `appVersion`.
* [`charts/dragonfly/README.md`](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f0 …
> chore: bump client to v0.2.34 and bump dragonfly to v2.2.4-beta.1

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request updates the `dragonfly` Helm chart to enhance functionality and improve versioning. The most significant changes include bumping the version of several images, adding a new configuration option (`distThreshold`) for disk space management, and updating documentation to reflect these changes.
* Updated the `dragonfly` chart version to `1.3.35` and the client, seed-client, and dfinit image tags to `v0.2.35`. (`charts/dragonfly/Chart.yaml`: [[1]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R6) [[2]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L45-R50); `charts/dragonfly/README.md`: [[3]](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f07d262cb7cda2783bL180-R180) …
> feat: add diskThreshold to dfdaemon and bump client to v0.2.35

- charts/dragonfly/Chart.yaml
- charts/dragonfly/templates/client/metrics-svc.yaml
- charts/dragonfly/templates/manager/metrics-svc.yaml
- charts/dragonfly/templates/scheduler/metrics-svc.yaml
- charts/dragonfly/templates/seed-client/metrics-svc.yaml
Correct metrics labels path to use specific config.
Related to #242.
> fix: correct metrics labels path to use specific config

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request updates the Dragonfly Helm chart to reflect new versions of its components and associated metadata. The changes include version bumps for the application and its dependencies, updates to image tags in multiple configuration files, and adjustments to the chart's annotations and documentation.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L6-R7): Updated `version` to `1.4.0` and `appVersion` to `2.3.0`.
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L30-R31): Adjusted annotations to reflect the version bump for Dragonfly (`v2.3.0`) and its client (`v1.0.0`).
* [`charts/dragonfly/Chart.yaml`](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180 …
> chore: bump client to v1.0.0 and dragonfly to v2.3.0

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request updates the Dragonfly Helm chart and related documentation to use the latest release candidate and client images. The main changes are version bumps for the Dragonfly components and client images, ensuring the chart references the most recent and stable versions.
**Version updates for Dragonfly components:**
* Updated `manager` and `scheduler` image tags from `v2.3.1-beta.0` to `v2.3.1-rc.2` in `values.yaml`, `README.md`, and `Chart.yaml` to use the latest release candidate. [[1]](diffhunk://#diff-e11a1bce6de1a9204ff3555f83b37165f2b1694c9d2073422a40daf6f8e9d63bL42-R42) [[2]](diffhunk://#diff-e11a1bce6de1a9204ff3555f83b37165f2b1694c9d2073422a40daf6f8e9d63bL325-R325) [[3]](diffhunk://#diff-ab3616a93a116bdedaf154d37cf22079e8e253578cc200f07d262cb7cda2783bL295-R295) …
> chore: bump dragonfly to v2.3.1-rc.2 and bump client to v1.0.9

- charts/dragonfly/Chart.yaml
- charts/dragonfly/README.md
- charts/dragonfly/values.yaml
This pull request updates the Dragonfly Helm chart and its documentation to use the latest versions of the Dragonfly components. The changes primarily focus on bumping the image tags for the manager, scheduler, client, seed-client, and dfinit components to ensure deployments use the most recent releases.
Version and image updates:
* Updated `version` to `1.4.8` and `appVersion` to `2.3.2` in `Chart.yaml` to reflect the new chart and application versions.
* Bumped image tags for `manager` and `scheduler` from `v2.3.1` to `v2.3.2` in `Chart.yaml`, `values.yaml`, and documentation. [[1]](diffhunk://#diff-4f1af1c75d649da63a213e6ee988180b73ee3e14278748908bb056e9cd29c883L42-R50) [[2]](diffhunk://#diff-e11a1bce6de1a9204ff3555f83b37165f2b1694c9d2073422a40daf6f8e9d63bL42-R42) …
> chore(deps): bump client to v1.0.21 and bump dragonfly to v2.3.2

- README.md
This pull request updates the `README.md` to improve the Community section by making it more welcoming and organized. It clarifies ways to get involved, updates links, and restructures contact information for better readability.
Community section improvements:
* Expanded the introduction to encourage community growth and clarified ways to get involved.
* Updated the GitHub Discussions link to use a reference-style link `[discussion]` for consistency.
* Reorganized mailing lists into a nested list for developers and maintainers, improving clarity.
* Changed the DingTalk entry to "DingTalk Group" and formatted the group number as inline code.
Formatting and cleanup:
* Removed redundant License section and ensured license information is referenced by link only.
> docs(README): update community description
